#Generated once for configuration of goals
#Config config/MoveLinGraspBack_goal.yaml
target_frame: ''
goal_pose:
  header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: ''
  pose:
    position:
      x: -10.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.064954
      w: 0.997888
linVel: 0.0
