target_pose:
  header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: '/map'
  pose:
    position:
      x: 0.483
      y: -1.11
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.904
      w: -0.427
